modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"
issueTrackerURL="https://github.com/Warsnake90/MusketModextraflavourFork"

[[mods]]
modId="musketmod"
version="1.20.1Forge-Fork-1.1.2"
displayName="Musket Mod"
#updateJSONURL=""
displayURL="https://github.com/Warsnake90/MusketModextraflavourFork"
logoFile="logo.png"
credits="lilypuree, MikhailTapio, Xannosz, SkpC9 for their contribution, -, SnowierPuppet(F), indeinerwand88(F), Toast3113(F)"
authors="ewewukek, Warsnake(Fork)"
description='''
Small mod that adds craftable muskets and pistols.
This is a forked version.
'''

[[dependencies.musketmod]]
modId="forge"
mandatory=true
versionRange="[47,)" # Minimum Forge version
ordering="NONE"
side="BOTH"

[[dependencies.musketmod]]
modId="minecraft"
mandatory=true
versionRange="1.20.1"
ordering="NONE"
side="BOTH"

[[dependencies.musketmod]]
modId="create"
mandatory=false
versionRange= "*"
ordering="AFTER"
side="BOTH"

[[dependencies.musketmod]]
modId="overgeared"
mandatory=true
versionRange= "*"
ordering="AFTER"
side="BOTH"
